export const TAX_CONSTANTS = {
	MIN_SALARY: 8647,
	LIVING_WAGE: 3328,
	ESV_RATE: 0.22,
	GROUP_1_TAX_RATE: 0.1, // 10% від прожиткового мінімуму
	GROUP_2_TAX_RATE: 0.2, // 20% від мінімальної зарплати
	GROUP_3_TAX_RATE: 0.05,
	EXCESS_TAX_RATE: 0.15, // Єдина ставка для всіх груп при перевищенні
	MILITARY_TAX_RATE_FIXED: 0.1, // 10% від МЗП для 1-2 груп
	MILITARY_TAX_RATE_GROUP_3: 0.01,
	MILITARY_TAX_RATE_GENERAL: 0.05,
	GENERAL_TAX_RATE: 0.18,
	MIN_INCOME_FOR_VAT: 1000000,
};

// Ліміти доходу на 2026 рік (МЗП * коефіцієнт)
// 1 група: 167 МЗП
// 2 група: 834 МЗП
// 3 група: 1167 МЗП
export const LIMITS = {
	1: TAX_CONSTANTS.MIN_SALARY * 167,
	2: TAX_CONSTANTS.MIN_SALARY * 834,
	3: TAX_CONSTANTS.MIN_SALARY * 1167,
};

export const CALCULATED_CONSTANTS = {
	ESV: TAX_CONSTANTS.MIN_SALARY * TAX_CONSTANTS.ESV_RATE,
	GROUP_1_TAX: TAX_CONSTANTS.LIVING_WAGE * TAX_CONSTANTS.GROUP_1_TAX_RATE,
	GROUP_2_TAX: TAX_CONSTANTS.MIN_SALARY * TAX_CONSTANTS.GROUP_2_TAX_RATE,
	MILITARY_TAX_FIXED:
		TAX_CONSTANTS.MIN_SALARY * TAX_CONSTANTS.MILITARY_TAX_RATE_FIXED,
	INCOME_LIMIT_GROUP_3: LIMITS[3], // Adding this back for backward compatibility if needed, though previously it was calculated
};
